<?php
    $kuchenka_gazowa = isset($_REQUEST['kuchenka_gazowa']) ? $_REQUEST['kuchenka_gazowa'] : '';
    $kuchenka_gazowa_szerokosc = isset($_REQUEST['kuchenka_gazowa_szerokosc']) ? $_REQUEST['kuchenka_gazowa_szerokosc'] : '';
    $kuchenka_indukcyjna = isset($_REQUEST['kuchenka_indukcyjna']) ? $_REQUEST['kuchenka_indukcyjna'] : '';
    $kuchenka_indukcyjna_szerokosc = isset($_REQUEST['kuchenka_indukcyjna_szerokosc']) ? $_REQUEST['kuchenka_indukcyjna_szerokosc'] : '';
    $okap_kuchenny_w_zabudowie = isset($_REQUEST['okap_kuchenny_w_zabudowie']) ? $_REQUEST['okap_kuchenny_w_zabudowie'] : '';
    $okap_kuchenny_zintegrowany_z_plyta = isset($_REQUEST['okap_kuchenny_zintegrowany_z_plyta']) ? $_REQUEST['okap_kuchenny_zintegrowany_z_plyta'] : '';
    $okap_kuchenny_podblatowy = isset($_REQUEST['okap_kuchenny_podblatowy']) ? $_REQUEST['okap_kuchenny_podblatowy'] : '';
    $okap_kuchenny_wiszacy = isset($_REQUEST['okap_kuchenny_wiszacy']) ? $_REQUEST['okap_kuchenny_wiszacy'] : '';
    $piekarnik_standardowy = isset($_REQUEST['piekarnik_standardowy']) ? $_REQUEST['piekarnik_standardowy'] : '';
    $piekarnik_standardowy_plyta = isset($_REQUEST['piekarnik_standardowy_plyta']) ? $_REQUEST['piekarnik_standardowy_plyta'] : '';
    $piekarnik_standardowy_slupek = isset($_REQUEST['piekarnik_standardowy_slupek']) ? $_REQUEST['piekarnik_standardowy_slupek'] : '';
    $piekarnik_z_funkcja_mikrofali = isset($_REQUEST['piekarnik_z_funkcja_mikrofali']) ? $_REQUEST['piekarnik_z_funkcja_mikrofali'] : '';
    $piekarnik_z_funkcja_mikrofali_plyta = isset($_REQUEST['piekarnik_z_funkcja_mikrofali_plyta']) ? $_REQUEST['piekarnik_z_funkcja_mikrofali_plyta'] : '';
    $piekarnik_z_funkcja_mikrofali_slupek = isset($_REQUEST['piekarnik_z_funkcja_mikrofali_slupek']) ? $_REQUEST['piekarnik_z_funkcja_mikrofali_slupek'] : '';
    $mikrofalowka_wolnostojaca = isset($_REQUEST['mikrofalowka_wolnostojaca']) ? $_REQUEST['mikrofalowka_wolnostojaca'] : '';
    $mikrofalowka_w_zabudowie = isset($_REQUEST['mikrofalowka_w_zabudowie']) ? $_REQUEST['mikrofalowka_w_zabudowie'] : '';
    $ekspres_do_kawy_wolnostojacy = isset($_REQUEST['ekspres_do_kawy_wolnostojacy']) ? $_REQUEST['ekspres_do_kawy_wolnostojacy'] : '';
    $ekspres_do_kawy_w_zabudowie = isset($_REQUEST['ekspres_do_kawy_w_zabudowie']) ? $_REQUEST['ekspres_do_kawy_w_zabudowie'] : '';
    $lodowka_w_zabudowie = isset($_REQUEST['lodowka_w_zabudowie']) ? $_REQUEST['lodowka_w_zabudowie'] : '';
    $lodowka_wolnostojaca = isset($_REQUEST['lodowka_wolnostojaca']) ? $_REQUEST['lodowka_wolnostojaca'] : '';
    $lodowka_wolnostojaca_side = isset($_REQUEST['lodowka_wolnostojaca_side']) ? $_REQUEST['lodowka_wolnostojaca_side'] : '';
    $lodowka_z_kostkarka = isset($_REQUEST['lodowka_z_kostkarka']) ? $_REQUEST['lodowka_z_kostkarka'] : '';
    $lodowka_do_wina = isset($_REQUEST['lodowka_do_wina']) ? $_REQUEST['lodowka_do_wina'] : '';
    $zmywarka_45cm_wolnostojaca = isset($_REQUEST['zmywarka_45cm_wolnostojaca']) ? $_REQUEST['zmywarka_45cm_wolnostojaca'] : '';
    $zmywarka_45cm_w_zabudowie = isset($_REQUEST['zmywarka_45cm_w_zabudowie']) ? $_REQUEST['zmywarka_45cm_w_zabudowie'] : '';
    $zmywarka_60cm_wolnostojaca = isset($_REQUEST['zmywarka_60cm_wolnostojaca']) ? $_REQUEST['zmywarka_60cm_wolnostojaca'] : '';
    $zmywarka_60cm_w_zabudowie = isset($_REQUEST['zmywarka_60cm_w_zabudowie']) ? $_REQUEST['zmywarka_60cm_w_zabudowie'] : '';
    $zlewozmywak_nablatowy = isset($_REQUEST['zlewozmywak_nablatowy']) ? $_REQUEST['zlewozmywak_nablatowy'] : '';
    $zlewozmywak_nablatowy_szerokosc = isset($_REQUEST['zlewozmywak_nablatowy_szerokosc']) ? $_REQUEST['zlewozmywak_nablatowy_szerokosc'] : '';
    $zlewozmywak_podblatowy = isset($_REQUEST['zlewozmywak_podblatowy']) ? $_REQUEST['zlewozmywak_podblatowy'] : '';
    $zlewozmywak_podblatowy_szerokosc = isset($_REQUEST['zlewozmywak_podblatowy_szerokosc']) ? $_REQUEST['zlewozmywak_podblatowy_szerokosc'] : '';
    $zlewozmywak_jednokomorowy = isset($_REQUEST['zlewozmywak_jednokomorowy']) ? $_REQUEST['zlewozmywak_jednokomorowy'] : '';
    $zlewozmywak_jednokomorowy_szerokosc = isset($_REQUEST['zlewozmywak_jednokomorowy_szerokosc']) ? $_REQUEST['zlewozmywak_jednokomorowy_szerokosc'] : '';
    $zlewozmywak_dwukomorowy = isset($_REQUEST['zlewozmywak_dwukomorowy']) ? $_REQUEST['zlewozmywak_dwukomorowy'] : '';
    $zlewozmywak_dwukomorowy_szerokosc = isset($_REQUEST['zlewozmywak_dwukomorowy_szerokosc']) ? $_REQUEST['zlewozmywak_dwukomorowy_szerokosc'] : '';
    $zlewozmywak_z_ociekaczem = isset($_REQUEST['zlewozmywak_z_ociekaczem']) ? $_REQUEST['zlewozmywak_z_ociekaczem'] : '';
    $zlewozmywak_z_ociekaczem_szerokosc = isset($_REQUEST['zlewozmywak_z_ociekaczem_szerokosc']) ? $_REQUEST['zlewozmywak_z_ociekaczem_szerokosc'] : '';
    $bateria_zlewozmywakowa = isset($_REQUEST['bateria_zlewozmywakowa']) ? $_REQUEST['bateria_zlewozmywakowa'] : '';
    $bateria_zlewozmywakowa_z_wyciagana_wylewka = isset($_REQUEST['bateria_zlewozmywakowa_z_wyciagana_wylewka']) ? $_REQUEST['bateria_zlewozmywakowa_z_wyciagana_wylewka'] : '';
    $bateria_zlewozmywakowa_z_filtrem = isset($_REQUEST['bateria_zlewozmywakowa_z_filtrem']) ? $_REQUEST['bateria_zlewozmywakowa_z_filtrem'] : '';
    $osobny_filtr_wody = isset($_REQUEST['osobny_filtr_wody']) ? $_REQUEST['osobny_filtr_wody'] : '';
    $bateria_zlewozmywakowa_z_funkcja_wody_mineralnej = isset($_REQUEST['bateria_zlewozmywakowa_z_funkcja_wody_mineralnej']) ? $_REQUEST['bateria_zlewozmywakowa_z_funkcja_wody_mineralnej'] : '';
    $bateria_zlewozmywakowa_z_funkcja_wrzatku = isset($_REQUEST['bateria_zlewozmywakowa_z_funkcja_wrzatku']) ? $_REQUEST['bateria_zlewozmywakowa_z_funkcja_wrzatku'] : '';
    $czajnik_elektryczny = isset($_REQUEST['czajnik_elektryczny']) ? $_REQUEST['czajnik_elektryczny'] : '';
    $robot_kuchenny = isset($_REQUEST['robot_kuchenny']) ? $_REQUEST['robot_kuchenny'] : '';
    $thermomix = isset($_REQUEST['thermomix']) ? $_REQUEST['thermomix'] : '';
    $krajalnica = isset($_REQUEST['krajalnica']) ? $_REQUEST['krajalnica'] : '';
    $toster = isset($_REQUEST['toster']) ? $_REQUEST['toster'] : '';
    $sokowirowka = isset($_REQUEST['sokowirowka']) ? $_REQUEST['sokowirowka'] : '';

    $kuchnia_inne_1 = isset($_REQUEST['kuchnia_inne_1']) ? $_REQUEST['kuchnia_inne_1'] : '';
    $kuchnia_inne_2 = isset($_REQUEST['kuchnia_inne_2']) ? $_REQUEST['kuchnia_inne_2'] : '';
    $kuchnia_inne_3 = isset($_REQUEST['kuchnia_inne_3']) ? $_REQUEST['kuchnia_inne_3'] : '';
    $kuchnia_inne_4 = isset($_REQUEST['kuchnia_inne_4']) ? $_REQUEST['kuchnia_inne_4'] : '';
    $kuchnia_inne_5 = isset($_REQUEST['kuchnia_inne_5']) ? $_REQUEST['kuchnia_inne_5'] : '';
    $kuchnia_inne_6 = isset($_REQUEST['kuchnia_inne_6']) ? $_REQUEST['kuchnia_inne_6'] : '';
    $kuchnia_inne_7 = isset($_REQUEST['kuchnia_inne_7']) ? $_REQUEST['kuchnia_inne_7'] : '';
    $kuchnia_inne_8 = isset($_REQUEST['kuchnia_inne_8']) ? $_REQUEST['kuchnia_inne_8'] : '';
  
if($wstecz != "true") {
    $SQL = [];
    //tresc zapytan
    array_push($SQL, "UPDATE a_kuchnia SET kuchenka_gazowa = '".$kuchenka_gazowa."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET kuchenka_gazowa_szerokosc = '".$kuchenka_gazowa_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET kuchenka_indukcyjna = '".$kuchenka_indukcyjna."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET kuchenka_indukcyjna_szerokosc = '".$kuchenka_indukcyjna_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET okap_kuchenny_w_zabudowie = '".$okap_kuchenny_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET okap_kuchenny_zintegrowany_z_plyta = '".$okap_kuchenny_zintegrowany_z_plyta."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET okap_kuchenny_podblatowy = '".$okap_kuchenny_podblatowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET okap_kuchenny_wiszacy = '".$okap_kuchenny_wiszacy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_standardowy = '".$piekarnik_standardowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_standardowy_plyta = '".$piekarnik_standardowy_plyta."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_standardowy_slupek = '".$piekarnik_standardowy_slupek."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_z_funkcja_mikrofali = '".$piekarnik_z_funkcja_mikrofali."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_z_funkcja_mikrofali_plyta = '".$piekarnik_z_funkcja_mikrofali_plyta."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET piekarnik_z_funkcja_mikrofali_slupek = '".$piekarnik_z_funkcja_mikrofali_slupek."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET mikrofalowka_wolnostojaca = '".$mikrofalowka_wolnostojaca."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET mikrofalowka_w_zabudowie = '".$mikrofalowka_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET ekspres_do_kawy_wolnostojacy = '".$ekspres_do_kawy_wolnostojacy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET ekspres_do_kawy_w_zabudowie = '".$ekspres_do_kawy_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET lodowka_w_zabudowie = '".$lodowka_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET lodowka_wolnostojaca = '".$lodowka_wolnostojaca."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET lodowka_wolnostojaca_side = '".$lodowka_wolnostojaca_side."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET lodowka_z_kostkarka = '".$lodowka_z_kostkarka."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET lodowka_do_wina = '".$lodowka_do_wina."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zmywarka_45cm_wolnostojaca = '".$zmywarka_45cm_wolnostojaca."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zmywarka_45cm_w_zabudowie = '".$zmywarka_45cm_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zmywarka_60cm_wolnostojaca = '".$zmywarka_60cm_wolnostojaca."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zmywarka_60cm_w_zabudowie = '".$zmywarka_60cm_w_zabudowie."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_nablatowy = '".$zlewozmywak_nablatowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_nablatowy_szerokosc = '".$zlewozmywak_nablatowy_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_podblatowy = '".$zlewozmywak_podblatowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_podblatowy_szerokosc = '".$zlewozmywak_podblatowy_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_jednokomorowy = '".$zlewozmywak_jednokomorowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_jednokomorowy_szerokosc = '".$zlewozmywak_jednokomorowy_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_dwukomorowy = '".$zlewozmywak_dwukomorowy."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_dwukomorowy_szerokosc = '".$zlewozmywak_dwukomorowy_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_z_ociekaczem = '".$zlewozmywak_z_ociekaczem."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET zlewozmywak_z_ociekaczem_szerokosc = '".$zlewozmywak_z_ociekaczem_szerokosc."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET bateria_zlewozmywakowa = '".$bateria_zlewozmywakowa."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET bateria_zlewozmywakowa_z_wyciagana_wylewka = '".$bateria_zlewozmywakowa_z_wyciagana_wylewka."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET bateria_zlewozmywakowa_z_filtrem = '".$bateria_zlewozmywakowa_z_filtrem."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET osobny_filtr_wody = '".$osobny_filtr_wody."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET bateria_zlewozmywakowa_z_funkcja_wody_mineralnej = '".$bateria_zlewozmywakowa_z_funkcja_wody_mineralnej."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET bateria_zlewozmywakowa_z_funkcja_wrzatku = '".$bateria_zlewozmywakowa_z_funkcja_wrzatku."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET czajnik_elektryczny = '".$czajnik_elektryczny."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET robot_kuchenny = '".$robot_kuchenny."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET thermomix = '".$thermomix."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET krajalnica = '".$krajalnica."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET toster = '".$toster."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET sokowirowka = '".$sokowirowka."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_1 = '".$kuchnia_inne_1."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_2 = '".$kuchnia_inne_2."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_3 = '".$kuchnia_inne_3."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_4 = '".$kuchnia_inne_4."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_5 = '".$kuchnia_inne_5."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_6 = '".$kuchnia_inne_6."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_7 = '".$kuchnia_inne_7."' WHERE ankietaID = ".$ankietaID.";");
    array_push($SQL, "UPDATE a_kuchnia SET inne_8 = '".$kuchnia_inne_8."' WHERE ankietaID = ".$ankietaID.";");

    //wykonanie zapytan
    for($s=0; $s<count($SQL); $s++) mysqli_query($conn, $SQL[$s]);
}
?>